# Generated by Django 3.1.7 on 2021-05-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210429_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='introduction',
        ),
    ]
